# Generated by Django 5.0.6 on 2024-07-01 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(default="Swallow Falls", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bulletlist",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bullet_list",
                to="resume.section",
            ),
        ),
        migrations.AlterField(
            model_name="bulletpoint",
            name="experience",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bullet_points",
                to="resume.experience",
            ),
        ),
    ]
