# Generated by Django 5.0.6 on 2024-07-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_experience_location_alter_bulletlist_section_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="category",
            new_name="name",
        ),
    ]
