# Generated by Django 5.0.6 on 2024-07-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_rename_category_section_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="sub_title",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="time_period",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="title",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="github",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="linkedin",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
