# Generated by Django 5.0.6 on 2024-07-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "resume",
            "0004_alter_experience_location_alter_experience_sub_title_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="BulletList",
        ),
    ]
