# Generated by Django 5.0.6 on 2024-07-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_userdata_alter_experience_time_period_resume_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume",
                to="resume.userdata",
            ),
        ),
    ]
