# Generated by Django 5.0.6 on 2024-07-24 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0007_alter_resume_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="resume.userdata",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="resume.resume",
            ),
        ),
    ]
