# Generated by Django 5.0.6 on 2024-07-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0008_section_user_alter_section_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="resume.userdata",
            ),
        ),
    ]
