# Generated by Django 5.0.6 on 2024-07-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0009_alter_section_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="display",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
